import type { Player } from "../../core/entities/Player";
import type { Team } from "../../core/entities/Team";
import type { TeamStaff } from "../../core/entities/TeamStaff";
import type { Competition } from "../../core/entities/Competition";
import type { PlayerTeamMembership } from "../../core/entities/PlayerTeamMembership";
import type { Official } from "../../core/entities/Official";
import type { Fixture } from "../../core/entities/Fixture";
import type { Venue } from "../../core/entities/Venue";
import { DEFAULT_TEAM_LOGO } from "../../core/entities/Team";
import { DEFAULT_STAFF_AVATAR } from "../../core/entities/TeamStaff";
import { DEFAULT_OFFICIAL_AVATAR } from "../../core/entities/Official";
import { DEFAULT_VENUE_IMAGE } from "../../core/entities/Venue";

export const SEED_ORGANIZATION_IDS = {
  CITY_FOOTBALL_LEAGUE: "org_default_1",
  REGIONAL_BASKETBALL_ASSOCIATION: "org_default_2",
  CRICKET_CHAMPIONS_NETWORK: "org_default_3",
  NATIONAL_FIELD_HOCKEY_ASSOCIATION: "org_default_4",
};

export const SEED_TEAM_IDS = {
  RED_DRAGONS_FC: "team_default_1",
  BLUE_THUNDER_UNITED: "team_default_2",
  GOLDEN_EAGLES: "team_default_3",
  STORM_BASKETBALL: "team_default_4",
  INTERNATIONAL_HAWKS: "team_default_5",
  GREEN_DRAGONS: "team_default_6",
};

export const SEED_COMPETITION_FORMAT_IDS = {
  STANDARD_LEAGUE: "format_standard_league",
  SINGLE_ELIMINATION: "format_single_elimination",
  DOUBLE_ELIMINATION: "format_double_elimination",
  GROUP_STAGE_KNOCKOUT: "format_group_knockout",
};

export const SEED_COMPETITION_IDS = {
  SUMMER_CUP_2026: "comp_default_1",
  PREMIER_LEAGUE_2026: "comp_default_2",
  BASKETBALL_SHOWCASE_2026: "comp_default_3",
  FIELD_HOCKEY_CHAMPIONSHIP_2026: "comp_default_4",
};

export const SEED_PLAYER_IDS = {
  CARLOS_MARTINEZ: "player_default_1",
  JOHN_SMITH: "player_default_2",
  YUKI_TANAKA: "player_default_3",
  MARCUS_JOHNSON: "player_default_4",
  DAVID_WILSON: "player_default_5",
  EMMA_RODRIGUEZ: "player_default_6",
  LUCAS_OLIVEIRA: "player_default_7",
  SOPHIE_MULLER: "player_default_8",
  KENJI_YAMAMOTO: "player_default_9",
  ANNA_KOWALSKI: "player_default_10",
};

export const SEED_STAFF_IDS = {
  HEAD_COACH_1: "staff_default_1",
  ASSISTANT_COACH_1: "staff_default_2",
  HEAD_COACH_2: "staff_default_3",
  PHYSIO_1: "staff_default_4",
  MANAGER_1: "staff_default_5",
};

export const SEED_OFFICIAL_IDS = {
  MICHAEL_ANDERSON: "official_default_1",
  SARAH_JOHNSON: "official_default_2",
  JAMES_WILLIAMS: "official_default_3",
  EMILY_DAVIS: "official_default_4",
};

export const SEED_FIXTURE_IDS = {
  FIXTURE_1: "fixture_default_1",
  FIXTURE_2: "fixture_default_2",
  FIXTURE_3: "fixture_default_3",
};

export const SEED_VENUE_IDS = {
  DRAGON_STADIUM: "venue_default_1",
  THUNDER_ARENA: "venue_default_2",
  EAGLE_NEST: "venue_default_3",
  STORM_CENTER: "venue_default_4",
  INTERNATIONAL_HOCKEY_ARENA: "venue_default_5",
};

function generate_current_timestamp(): string {
  return new Date().toISOString();
}

export function create_seed_players(
  position_id_goalkeeper: string,
  position_id_defender: string,
  position_id_midfielder: string,
  position_id_forward: string,
): Player[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_PLAYER_IDS.CARLOS_MARTINEZ,
      first_name: "Carlos",
      last_name: "Martinez",
      email: "carlos.martinez@reddragons.com",
      phone: "+1-555-2001",
      date_of_birth: "1995-03-15",
      position_id: position_id_forward,
      height_cm: 180,
      weight_kg: 75,
      nationality: "Spain",
      profile_image_url: "",
      emergency_contact_name: "Maria Martinez",
      emergency_contact_phone: "+1-555-2101",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.JOHN_SMITH,
      first_name: "John",
      last_name: "Smith",
      email: "john.smith@reddragons.com",
      phone: "+1-555-2002",
      date_of_birth: "1998-07-22",
      position_id: position_id_midfielder,
      height_cm: 175,
      weight_kg: 72,
      nationality: "United States",
      profile_image_url: "",
      emergency_contact_name: "Jane Smith",
      emergency_contact_phone: "+1-555-2102",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.YUKI_TANAKA,
      first_name: "Yuki",
      last_name: "Tanaka",
      email: "yuki.tanaka@bluethunder.com",
      phone: "+1-555-2003",
      date_of_birth: "1997-11-08",
      position_id: position_id_goalkeeper,
      height_cm: 188,
      weight_kg: 82,
      nationality: "Japan",
      profile_image_url: "",
      emergency_contact_name: "Kenji Tanaka",
      emergency_contact_phone: "+1-555-2103",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.MARCUS_JOHNSON,
      first_name: "Marcus",
      last_name: "Johnson",
      email: "marcus.johnson@bluethunder.com",
      phone: "+1-555-2004",
      date_of_birth: "1996-05-30",
      position_id: position_id_forward,
      height_cm: 190,
      weight_kg: 85,
      nationality: "United States",
      profile_image_url: "",
      emergency_contact_name: "Linda Johnson",
      emergency_contact_phone: "+1-555-2104",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.DAVID_WILSON,
      first_name: "David",
      last_name: "Wilson",
      email: "david.wilson@reddragons.com",
      phone: "+1-555-2005",
      date_of_birth: "1999-02-14",
      position_id: position_id_defender,
      height_cm: 185,
      weight_kg: 78,
      nationality: "England",
      profile_image_url: "",
      emergency_contact_name: "Sarah Wilson",
      emergency_contact_phone: "+1-555-2105",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.EMMA_RODRIGUEZ,
      first_name: "Emma",
      last_name: "Rodriguez",
      email: "emma.rodriguez@bluethunder.com",
      phone: "+1-555-2006",
      date_of_birth: "2000-09-18",
      position_id: position_id_midfielder,
      height_cm: 168,
      weight_kg: 62,
      nationality: "Argentina",
      profile_image_url: "",
      emergency_contact_name: "Carlos Rodriguez",
      emergency_contact_phone: "+1-555-2106",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.LUCAS_OLIVEIRA,
      first_name: "Lucas",
      last_name: "Oliveira",
      email: "lucas.oliveira@goldeneagles.com",
      phone: "+1-555-2007",
      date_of_birth: "1994-12-03",
      position_id: position_id_defender,
      height_cm: 183,
      weight_kg: 80,
      nationality: "Brazil",
      profile_image_url: "",
      emergency_contact_name: "Ana Oliveira",
      emergency_contact_phone: "+1-555-2107",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.SOPHIE_MULLER,
      first_name: "Sophie",
      last_name: "Muller",
      email: "sophie.muller@goldeneagles.com",
      phone: "+1-555-2008",
      date_of_birth: "1998-04-25",
      position_id: position_id_midfielder,
      height_cm: 170,
      weight_kg: 65,
      nationality: "Germany",
      profile_image_url: "",
      emergency_contact_name: "Hans Muller",
      emergency_contact_phone: "+1-555-2108",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.KENJI_YAMAMOTO,
      first_name: "Kenji",
      last_name: "Yamamoto",
      email: "kenji.yamamoto@goldeneagles.com",
      phone: "+1-555-2009",
      date_of_birth: "1997-08-10",
      position_id: position_id_goalkeeper,
      height_cm: 186,
      weight_kg: 84,
      nationality: "Japan",
      profile_image_url: "",
      emergency_contact_name: "Yoko Yamamoto",
      emergency_contact_phone: "+1-555-2109",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_PLAYER_IDS.ANNA_KOWALSKI,
      first_name: "Anna",
      last_name: "Kowalski",
      email: "anna.kowalski@reddragons.com",
      phone: "+1-555-2010",
      date_of_birth: "2001-06-20",
      position_id: position_id_forward,
      height_cm: 172,
      weight_kg: 66,
      nationality: "Poland",
      profile_image_url: "",
      emergency_contact_name: "Jan Kowalski",
      emergency_contact_phone: "+1-555-2110",
      medical_notes: "",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_teams(
  dragon_stadium_id: string,
  thunder_arena_id: string,
  eagle_nest_id: string,
  storm_center_id: string,
  international_hockey_arena_id: string,
): Team[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      name: "Red Dragons FC",
      short_name: "RDF",
      description: "Established football club with a strong youth program",
      organization_id: SEED_ORGANIZATION_IDS.CITY_FOOTBALL_LEAGUE,
      captain_player_id: SEED_PLAYER_IDS.CARLOS_MARTINEZ,
      vice_captain_player_id: SEED_PLAYER_IDS.DAVID_WILSON,
      max_squad_size: 25,
      home_venue_id: dragon_stadium_id,
      primary_color: "#DC2626",
      secondary_color: "#FFFFFF",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://reddragons.example.com",
      founded_year: 2010,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      name: "Blue Thunder United",
      short_name: "BTU",
      description: "Competitive club focusing on tactical excellence",
      organization_id: SEED_ORGANIZATION_IDS.CITY_FOOTBALL_LEAGUE,
      captain_player_id: SEED_PLAYER_IDS.YUKI_TANAKA,
      vice_captain_player_id: SEED_PLAYER_IDS.MARCUS_JOHNSON,
      max_squad_size: 25,
      home_venue_id: thunder_arena_id,
      primary_color: "#2563EB",
      secondary_color: "#F0F9FF",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://bluethunder.example.com",
      founded_year: 2012,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      name: "Golden Eagles",
      short_name: "GEA",
      description: "Championship-winning team with experienced squad",
      organization_id: SEED_ORGANIZATION_IDS.CITY_FOOTBALL_LEAGUE,
      captain_player_id: SEED_PLAYER_IDS.LUCAS_OLIVEIRA,
      vice_captain_player_id: SEED_PLAYER_IDS.SOPHIE_MULLER,
      max_squad_size: 28,
      home_venue_id: eagle_nest_id,
      primary_color: "#F59E0B",
      secondary_color: "#1F2937",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://goldeneagles.example.com",
      founded_year: 2008,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.STORM_BASKETBALL,
      name: "Storm Basketball",
      short_name: "STB",
      description: "Professional basketball team",
      organization_id: SEED_ORGANIZATION_IDS.REGIONAL_BASKETBALL_ASSOCIATION,
      captain_player_id: null,
      vice_captain_player_id: null,
      max_squad_size: 15,
      home_venue_id: storm_center_id,
      primary_color: "#7C3AED",
      secondary_color: "#EDE9FE",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://stormbasketball.example.com",
      founded_year: 2015,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.INTERNATIONAL_HAWKS,
      name: "International Hawks",
      short_name: "IH",
      description: "Elite field hockey team competing at international level",
      organization_id: SEED_ORGANIZATION_IDS.NATIONAL_FIELD_HOCKEY_ASSOCIATION,
      captain_player_id: null,
      vice_captain_player_id: null,
      max_squad_size: 16,
      home_venue_id: international_hockey_arena_id,
      primary_color: "#1F2937",
      secondary_color: "#FBBF24",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://internationalhawks.example.com",
      founded_year: 2005,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_TEAM_IDS.GREEN_DRAGONS,
      name: "Green Dragons",
      short_name: "GD",
      description: "Dynamic field hockey team with strong defensive lineup",
      organization_id: SEED_ORGANIZATION_IDS.NATIONAL_FIELD_HOCKEY_ASSOCIATION,
      captain_player_id: null,
      vice_captain_player_id: null,
      max_squad_size: 16,
      home_venue_id: dragon_stadium_id,
      primary_color: "#16A34A",
      secondary_color: "#E0F2FE",
      logo_url: DEFAULT_TEAM_LOGO,
      website: "https://greendragon.example.com",
      founded_year: 2010,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_team_staff(
  head_coach_role_id: string,
  assistant_coach_role_id: string,
  physio_role_id: string,
  team_manager_role_id: string,
): TeamStaff[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_STAFF_IDS.HEAD_COACH_1,
      first_name: "Roberto",
      last_name: "Garcia",
      email: "roberto.garcia@reddragons.com",
      phone: "+1-555-3001",
      date_of_birth: "1975-04-12",
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      role_id: head_coach_role_id,
      nationality: "Spain",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2020-01-15",
      employment_end_date: null,
      emergency_contact_name: "Carmen Garcia",
      emergency_contact_phone: "+1-555-3101",
      notes: "UEFA Pro License holder with 20 years of coaching experience",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.ASSISTANT_COACH_1,
      first_name: "Michael",
      last_name: "Thompson",
      email: "michael.thompson@reddragons.com",
      phone: "+1-555-3002",
      date_of_birth: "1982-08-25",
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      role_id: assistant_coach_role_id,
      nationality: "England",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2021-06-01",
      employment_end_date: null,
      emergency_contact_name: "Lisa Thompson",
      emergency_contact_phone: "+1-555-3102",
      notes: "Former professional player",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.HEAD_COACH_2,
      first_name: "Hiroshi",
      last_name: "Nakamura",
      email: "hiroshi.nakamura@bluethunder.com",
      phone: "+1-555-3003",
      date_of_birth: "1970-11-30",
      team_id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      role_id: head_coach_role_id,
      nationality: "Japan",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2019-08-01",
      employment_end_date: null,
      emergency_contact_name: "Yuki Nakamura",
      emergency_contact_phone: "+1-555-3103",
      notes: "Known for developing young talent",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.PHYSIO_1,
      first_name: "Sarah",
      last_name: "Chen",
      email: "sarah.chen@reddragons.com",
      phone: "+1-555-3004",
      date_of_birth: "1985-03-17",
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      role_id: physio_role_id,
      nationality: "Canada",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2022-02-01",
      employment_end_date: null,
      emergency_contact_name: "David Chen",
      emergency_contact_phone: "+1-555-3104",
      notes: "Certified Sports Physiotherapist",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_STAFF_IDS.MANAGER_1,
      first_name: "James",
      last_name: "O'Brien",
      email: "james.obrien@goldeneagles.com",
      phone: "+1-555-3005",
      date_of_birth: "1968-07-08",
      team_id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      role_id: team_manager_role_id,
      nationality: "Ireland",
      profile_image_url: DEFAULT_STAFF_AVATAR,
      employment_start_date: "2015-01-10",
      employment_end_date: null,
      emergency_contact_name: "Mary O'Brien",
      emergency_contact_phone: "+1-555-3105",
      notes: "10 years with the club, handles all administrative duties",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_competitions(
  competition_format_id: string,
): Competition[] {
  const now = generate_current_timestamp();
  const next_month = new Date();
  next_month.setMonth(next_month.getMonth() + 1);
  const three_months = new Date();
  three_months.setMonth(three_months.getMonth() + 3);

  return [
    {
      id: SEED_COMPETITION_IDS.SUMMER_CUP_2026,
      name: "Summer Cup 2026",
      description: "Annual summer football tournament featuring the best teams",
      organization_id: SEED_ORGANIZATION_IDS.CITY_FOOTBALL_LEAGUE,
      competition_format_id: competition_format_id,
      team_ids: [
        SEED_TEAM_IDS.RED_DRAGONS_FC,
        SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
        SEED_TEAM_IDS.GOLDEN_EAGLES,
      ],
      auto_generate_fixtures_and_assign_officials: false,
      start_date: next_month.toISOString().split("T")[0],
      end_date: three_months.toISOString().split("T")[0],
      registration_deadline: new Date().toISOString().split("T")[0],
      max_teams: 16,
      entry_fee: 500,
      prize_pool: 10000,
      location: "City Stadium",
      rule_overrides: {},
      status: "upcoming",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_COMPETITION_IDS.PREMIER_LEAGUE_2026,
      name: "Premier League Season 2026",
      description: "Full season league competition with home and away fixtures",
      organization_id: SEED_ORGANIZATION_IDS.CITY_FOOTBALL_LEAGUE,
      competition_format_id: competition_format_id,
      team_ids: [
        SEED_TEAM_IDS.RED_DRAGONS_FC,
        SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
        SEED_TEAM_IDS.GOLDEN_EAGLES,
      ],
      auto_generate_fixtures_and_assign_officials: false,
      start_date: "2026-01-15",
      end_date: "2026-06-30",
      registration_deadline: "2026-01-01",
      max_teams: 20,
      entry_fee: 1000,
      prize_pool: 50000,
      location: "Various Venues",
      rule_overrides: {},
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_COMPETITION_IDS.BASKETBALL_SHOWCASE_2026,
      name: "Basketball Showcase 2026",
      description: "Regional basketball championship",
      organization_id: SEED_ORGANIZATION_IDS.REGIONAL_BASKETBALL_ASSOCIATION,
      competition_format_id: competition_format_id,
      team_ids: [SEED_TEAM_IDS.STORM_BASKETBALL],
      auto_generate_fixtures_and_assign_officials: false,
      start_date: next_month.toISOString().split("T")[0],
      end_date: three_months.toISOString().split("T")[0],
      registration_deadline: new Date().toISOString().split("T")[0],
      max_teams: 12,
      entry_fee: 750,
      prize_pool: 15000,
      location: "Arena Sports Complex",
      rule_overrides: {},
      status: "upcoming",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_COMPETITION_IDS.FIELD_HOCKEY_CHAMPIONSHIP_2026,
      name: "International Field Hockey Championship 2026",
      description:
        "Premier field hockey competition featuring top international teams",
      organization_id: SEED_ORGANIZATION_IDS.NATIONAL_FIELD_HOCKEY_ASSOCIATION,
      competition_format_id: competition_format_id,
      team_ids: [
        SEED_TEAM_IDS.INTERNATIONAL_HAWKS,
        SEED_TEAM_IDS.GREEN_DRAGONS,
      ],
      auto_generate_fixtures_and_assign_officials: false,
      start_date: next_month.toISOString().split("T")[0],
      end_date: three_months.toISOString().split("T")[0],
      registration_deadline: new Date().toISOString().split("T")[0],
      max_teams: 8,
      entry_fee: 2000,
      prize_pool: 25000,
      location: "International Hockey Arena",
      rule_overrides: {},
      status: "upcoming",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_player_team_memberships(): PlayerTeamMembership[] {
  const now = generate_current_timestamp();

  return [
    {
      id: "player_team_membership_default_1",
      player_id: SEED_PLAYER_IDS.CARLOS_MARTINEZ,
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 9,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_2",
      player_id: SEED_PLAYER_IDS.JOHN_SMITH,
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 10,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_3",
      player_id: SEED_PLAYER_IDS.DAVID_WILSON,
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 4,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_4",
      player_id: SEED_PLAYER_IDS.ANNA_KOWALSKI,
      team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 11,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_5",
      player_id: SEED_PLAYER_IDS.YUKI_TANAKA,
      team_id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 1,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_6",
      player_id: SEED_PLAYER_IDS.MARCUS_JOHNSON,
      team_id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 7,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_7",
      player_id: SEED_PLAYER_IDS.EMMA_RODRIGUEZ,
      team_id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 8,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_8",
      player_id: SEED_PLAYER_IDS.LUCAS_OLIVEIRA,
      team_id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 5,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_9",
      player_id: SEED_PLAYER_IDS.SOPHIE_MULLER,
      team_id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 6,
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: "player_team_membership_default_10",
      player_id: SEED_PLAYER_IDS.KENJI_YAMAMOTO,
      team_id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      start_date: "2024-01-01",
      end_date: null,
      jersey_number: 1,
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_officials(
  organization_id: string,
  referee_role_id: string | null,
): Official[] {
  const now = generate_current_timestamp();

  return [
    {
      id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
      first_name: "Michael",
      last_name: "Anderson",
      email: "michael.anderson@officials.com",
      phone: "+1-555-4001",
      date_of_birth: "1978-06-15",
      organization_id: organization_id,
      primary_role_id: referee_role_id,
      years_of_experience: 15,
      nationality: "United States",
      profile_image_url: DEFAULT_OFFICIAL_AVATAR,
      emergency_contact_name: "Susan Anderson",
      emergency_contact_phone: "+1-555-4101",
      notes: "FIFA certified referee",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
      first_name: "Sarah",
      last_name: "Johnson",
      email: "sarah.johnson@officials.com",
      phone: "+1-555-4002",
      date_of_birth: "1985-02-20",
      organization_id: organization_id,
      primary_role_id: referee_role_id,
      years_of_experience: 10,
      nationality: "Canada",
      profile_image_url: DEFAULT_OFFICIAL_AVATAR,
      emergency_contact_name: "Tom Johnson",
      emergency_contact_phone: "+1-555-4102",
      notes: "Specializes in high-profile matches",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
      first_name: "James",
      last_name: "Williams",
      email: "james.williams@officials.com",
      phone: "+1-555-4003",
      date_of_birth: "1982-09-10",
      organization_id: organization_id,
      primary_role_id: referee_role_id,
      years_of_experience: 12,
      nationality: "England",
      profile_image_url: DEFAULT_OFFICIAL_AVATAR,
      emergency_contact_name: "Kate Williams",
      emergency_contact_phone: "+1-555-4103",
      notes: "UEFA qualified assistant referee",
      status: "active",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
      first_name: "Emily",
      last_name: "Davis",
      email: "emily.davis@officials.com",
      phone: "+1-555-4004",
      date_of_birth: "1990-11-28",
      organization_id: organization_id,
      primary_role_id: referee_role_id,
      years_of_experience: 7,
      nationality: "Australia",
      profile_image_url: DEFAULT_OFFICIAL_AVATAR,
      emergency_contact_name: "Mark Davis",
      emergency_contact_phone: "+1-555-4104",
      notes: "Rising star in officiating community",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_fixtures(
  referee_role_id: string,
  assistant_referee_role_id: string,
): Fixture[] {
  const now = generate_current_timestamp();
  const next_week = new Date();
  next_week.setDate(next_week.getDate() + 7);
  const two_weeks = new Date();
  two_weeks.setDate(two_weeks.getDate() + 14);
  const three_weeks = new Date();
  three_weeks.setDate(three_weeks.getDate() + 21);

  return [
    {
      id: SEED_FIXTURE_IDS.FIXTURE_1,
      competition_id: SEED_COMPETITION_IDS.PREMIER_LEAGUE_2026,
      round_number: 1,
      round_name: "Round 1",
      home_team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      away_team_id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      venue: "Dragon Stadium",
      scheduled_date: next_week.toISOString().split("T")[0],
      scheduled_time: "15:00",
      home_team_score: null,
      away_team_score: null,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Referee",
        },
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: assistant_referee_role_id,
          role_name: "Assistant Referee 1",
        },
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: assistant_referee_role_id,
          role_name: "Assistant Referee 2",
        },
      ],
      game_events: [],
      current_period: "pre_game",
      current_minute: 0,
      match_day: 1,
      notes: "Season opener - expected high attendance",
      status: "scheduled",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_FIXTURE_IDS.FIXTURE_2,
      competition_id: SEED_COMPETITION_IDS.PREMIER_LEAGUE_2026,
      round_number: 1,
      round_name: "Round 1",
      home_team_id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      away_team_id: SEED_TEAM_IDS.RED_DRAGONS_FC,
      venue: "Eagle Nest Stadium",
      scheduled_date: two_weeks.toISOString().split("T")[0],
      scheduled_time: "18:30",
      home_team_score: null,
      away_team_score: null,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: referee_role_id,
          role_name: "Referee",
        },
        {
          official_id: SEED_OFFICIAL_IDS.JAMES_WILLIAMS,
          role_id: assistant_referee_role_id,
          role_name: "Assistant Referee 1",
        },
      ],
      game_events: [],
      current_period: "pre_game",
      current_minute: 0,
      match_day: 1,
      notes: "Evening match under lights",
      status: "scheduled",
      created_at: now,
      updated_at: now,
    },
    {
      id: SEED_FIXTURE_IDS.FIXTURE_3,
      competition_id: SEED_COMPETITION_IDS.PREMIER_LEAGUE_2026,
      round_number: 2,
      round_name: "Round 2",
      home_team_id: SEED_TEAM_IDS.BLUE_THUNDER_UNITED,
      away_team_id: SEED_TEAM_IDS.GOLDEN_EAGLES,
      venue: "Thunder Arena",
      scheduled_date: three_weeks.toISOString().split("T")[0],
      scheduled_time: "14:00",
      home_team_score: null,
      away_team_score: null,
      assigned_officials: [
        {
          official_id: SEED_OFFICIAL_IDS.MICHAEL_ANDERSON,
          role_id: referee_role_id,
          role_name: "Referee",
        },
        {
          official_id: SEED_OFFICIAL_IDS.SARAH_JOHNSON,
          role_id: assistant_referee_role_id,
          role_name: "Assistant Referee 1",
        },
        {
          official_id: SEED_OFFICIAL_IDS.EMILY_DAVIS,
          role_id: assistant_referee_role_id,
          role_name: "Assistant Referee 2",
        },
      ],
      game_events: [],
      current_period: "pre_game",
      current_minute: 0,
      match_day: 2,
      notes: "Key match for league standings",
      status: "scheduled",
      created_at: now,
      updated_at: now,
    },
  ];
}

export function create_seed_venues(): Omit<
  Venue,
  "id" | "created_at" | "updated_at"
>[] {
  return [
    {
      name: "Dragon Stadium",
      short_name: "DS",
      address: "123 Sports Avenue",
      city: "Manchester",
      country: "United Kingdom",
      capacity: 25000,
      surface_type: "grass",
      has_lighting: true,
      has_parking: true,
      contact_email: "info@dragonstadium.example.com",
      contact_phone: "+44-555-0101",
      website: "https://dragonstadium.example.com",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
    },
    {
      name: "Thunder Arena",
      short_name: "TA",
      address: "456 Champions Road",
      city: "London",
      country: "United Kingdom",
      capacity: 40000,
      surface_type: "grass",
      has_lighting: true,
      has_parking: true,
      contact_email: "bookings@thunderarena.example.com",
      contact_phone: "+44-555-0202",
      website: "https://thunderarena.example.com",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
    },
    {
      name: "Eagle Nest Stadium",
      short_name: "ENS",
      address: "789 Victory Lane",
      city: "Birmingham",
      country: "United Kingdom",
      capacity: 35000,
      surface_type: "grass",
      has_lighting: true,
      has_parking: true,
      contact_email: "events@eaglenest.example.com",
      contact_phone: "+44-555-0303",
      website: "https://eaglenest.example.com",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
    },
    {
      name: "Storm Center",
      short_name: "SC",
      address: "321 Basketball Boulevard",
      city: "Chicago",
      country: "United States",
      capacity: 18000,
      surface_type: "indoor",
      has_lighting: true,
      has_parking: true,
      contact_email: "info@stormcenter.example.com",
      contact_phone: "+1-555-0404",
      website: "https://stormcenter.example.com",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
    },
    {
      name: "International Hockey Arena",
      short_name: "IHA",
      address: "555 Olympic Way",
      city: "Amsterdam",
      country: "Netherlands",
      capacity: 12000,
      surface_type: "artificial_turf",
      has_lighting: true,
      has_parking: true,
      contact_email: "info@internationalhockeyarena.example.com",
      contact_phone: "+31-555-0505",
      website: "https://internationalhockeyarena.example.com",
      image_url: DEFAULT_VENUE_IMAGE,
      status: "active",
    },
  ];
}
